# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('college_name', models.CharField(max_length=100)),
                ('college_place', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('skill1', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('post', models.TextField()),
                ('profile_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
